"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / '.env')
IS_TESTING = 'test' in sys.argv


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name):
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]


def env_int(name, default):
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError) as exc:
        raise ImproperlyConfigured(f'{name} must be an integer.') from exc


ENVIRONMENT = os.environ.get('DJANGO_ENVIRONMENT', 'development').strip().lower()
if ENVIRONMENT not in {'development', 'production'}:
    raise ImproperlyConfigured(
        'DJANGO_ENVIRONMENT must be either development or production.'
    )
IS_PRODUCTION = ENVIRONMENT == 'production'

# Tests receive a deterministic, non-production key so the suite remains
# self-contained. Every other environment must provide its own secret.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY and IS_TESTING:
    SECRET_KEY = 'characterization-tests-only-not-for-runtime'
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY is required. Copy .env.example to .env and generate a unique secret.'
    )
if IS_PRODUCTION and (
    len(SECRET_KEY) < 50
    or SECRET_KEY.startswith('django-insecure-')
    or 'replace-with' in SECRET_KEY
):
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be a unique production secret of at least 50 characters.'
    )

DEBUG = env_bool('DJANGO_DEBUG', not IS_PRODUCTION)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured('DJANGO_DEBUG cannot be enabled in production.')

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS')
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS is required in production.')

# Production defaults pass Django's deployment checklist. HSTS preload is
# deliberately scoped to the explicit production profile, never development.
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', IS_PRODUCTION and not IS_TESTING)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', IS_PRODUCTION and not IS_TESTING)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', IS_PRODUCTION and not IS_TESTING)
SECURE_HSTS_SECONDS = env_int(
    'DJANGO_SECURE_HSTS_SECONDS', 31536000 if IS_PRODUCTION and not IS_TESTING else 0
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', IS_PRODUCTION and not IS_TESTING
)
SECURE_HSTS_PRELOAD = env_bool(
    'DJANGO_SECURE_HSTS_PRELOAD', IS_PRODUCTION and not IS_TESTING
)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

if env_bool('DJANGO_TRUST_X_FORWARDED_PROTO', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    # Local apps
    'users',
    'clients',
    'cases',
    'tasks',
    'events',
    'notes',
    'finance',
    'documents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL is the permanent default for development and production. SQLite
# remains available only as an explicit, non-production recovery/export mode.
DATABASE_ENGINE = os.environ.get('DJANGO_DB_ENGINE', 'postgresql').strip().lower()

if DATABASE_ENGINE in {'postgresql', 'postgres'}:
    database_name = os.environ.get('DJANGO_DB_NAME', 'gesavo').strip()
    database_user = os.environ.get('DJANGO_DB_USER', 'gesavo').strip()
    database_password = os.environ.get('DJANGO_DB_PASSWORD', '')
    database_host = os.environ.get('DJANGO_DB_HOST', '127.0.0.1').strip()
    database_port = env_int('DJANGO_DB_PORT', 5432)
    database_sslmode = os.environ.get(
        'DJANGO_DB_SSLMODE', 'require' if IS_PRODUCTION else 'prefer'
    ).strip().lower()

    if not database_password:
        raise ImproperlyConfigured('DJANGO_DB_PASSWORD is required for PostgreSQL.')
    if IS_PRODUCTION:
        if len(database_password) < 16 or 'replace-with' in database_password:
            raise ImproperlyConfigured(
                'DJANGO_DB_PASSWORD must be a non-placeholder production secret '
                'of at least 16 characters.'
            )
        required_database_values = {
            'DJANGO_DB_NAME': database_name,
            'DJANGO_DB_USER': database_user,
            'DJANGO_DB_HOST': os.environ.get('DJANGO_DB_HOST', '').strip(),
        }
        missing_database_values = [
            name for name, value in required_database_values.items() if not value
        ]
        if missing_database_values:
            raise ImproperlyConfigured(
                f"Missing production database settings: {', '.join(missing_database_values)}."
            )

    allowed_ssl_modes = {'disable', 'allow', 'prefer', 'require', 'verify-ca', 'verify-full'}
    if database_sslmode not in allowed_ssl_modes:
        raise ImproperlyConfigured(
            'DJANGO_DB_SSLMODE must be one of: '
            f"{', '.join(sorted(allowed_ssl_modes))}."
        )
    if IS_PRODUCTION and database_sslmode not in {'require', 'verify-ca', 'verify-full'}:
        raise ImproperlyConfigured(
            'DJANGO_DB_SSLMODE must require TLS in production.'
        )

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': database_name,
            'USER': database_user,
            'PASSWORD': database_password,
            'HOST': database_host,
            'PORT': database_port,
            'CONN_MAX_AGE': env_int('DJANGO_DB_CONN_MAX_AGE', 60 if IS_PRODUCTION else 0),
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                'sslmode': database_sslmode,
                'connect_timeout': env_int('DJANGO_DB_CONNECT_TIMEOUT', 10),
            },
        }
    }

    test_database_name = os.environ.get('DJANGO_TEST_DB_NAME', '').strip()
    if test_database_name:
        DATABASES['default']['TEST'] = {'NAME': test_database_name}
elif DATABASE_ENGINE == 'sqlite':
    if IS_PRODUCTION:
        raise ImproperlyConfigured('SQLite is not supported in production.')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(
                os.environ.get('DJANGO_SQLITE_PATH', str(BASE_DIR / 'db.sqlite3'))
            ),
        }
    }
else:
    raise ImproperlyConfigured(
        'DJANGO_DB_ENGINE must be postgresql (default) or sqlite (recovery only).'
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Legacy media root is retained only so migration 0003 can relocate historical
# files. New documents use a dedicated private storage with no public URL.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
PRIVATE_DOCUMENT_ROOT = Path(
    os.environ.get('DJANGO_PRIVATE_DOCUMENT_ROOT', BASE_DIR / 'private_media')
)
if IS_PRODUCTION and not os.environ.get('DJANGO_PRIVATE_DOCUMENT_ROOT', '').strip():
    raise ImproperlyConfigured(
        'DJANGO_PRIVATE_DOCUMENT_ROOT is required in production and must not be web-served.'
    )
if PRIVATE_DOCUMENT_ROOT.resolve() == Path(MEDIA_ROOT).resolve():
    raise ImproperlyConfigured(
        'DJANGO_PRIVATE_DOCUMENT_ROOT must be separate from the legacy MEDIA_ROOT.'
    )

DOCUMENT_MAX_UPLOAD_SIZE_MB = env_int('DOCUMENT_MAX_UPLOAD_SIZE_MB', 10)
if DOCUMENT_MAX_UPLOAD_SIZE_MB <= 0:
    raise ImproperlyConfigured('DOCUMENT_MAX_UPLOAD_SIZE_MB must be positive.')
DOCUMENT_MAX_UPLOAD_SIZE = DOCUMENT_MAX_UPLOAD_SIZE_MB * 1024 * 1024

TASK_ARCHIVE_AFTER_HOURS = env_int('TASK_ARCHIVE_AFTER_HOURS', 48)
TASK_ARCHIVE_INTERVAL_SECONDS = env_int('TASK_ARCHIVE_INTERVAL_SECONDS', 3600)
if TASK_ARCHIVE_AFTER_HOURS <= 0 or TASK_ARCHIVE_INTERVAL_SECONDS <= 0:
    raise ImproperlyConfigured(
        'TASK_ARCHIVE_AFTER_HOURS and TASK_ARCHIVE_INTERVAL_SECONDS must be positive.'
    )

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.CustomUser'

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = env_list('DJANGO_CORS_ALLOWED_ORIGINS')
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')
CORS_ALLOW_CREDENTIALS = False

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# SimpleJWT Settings
JWT_ACCESS_TOKEN_MINUTES = env_int('JWT_ACCESS_TOKEN_MINUTES', 15)
JWT_REFRESH_TOKEN_DAYS = env_int('JWT_REFRESH_TOKEN_DAYS', 1)
if JWT_ACCESS_TOKEN_MINUTES <= 0 or JWT_REFRESH_TOKEN_DAYS <= 0:
    raise ImproperlyConfigured(
        'JWT_ACCESS_TOKEN_MINUTES and JWT_REFRESH_TOKEN_DAYS must be positive integers.'
    )

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=JWT_ACCESS_TOKEN_MINUTES),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=JWT_REFRESH_TOKEN_DAYS),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    # Embed a fingerprint of the password hash and reject tokens issued before
    # a password change/reset.
    'CHECK_REVOKE_TOKEN': True,
}

# Password reset email settings.
# Development uses console output so reset links are visible in the backend terminal.
# For production, replace these values with SMTP configuration.
FRONTEND_URL = os.environ.get('FRONTEND_URL', '' if IS_PRODUCTION else 'http://localhost:3000')
if IS_PRODUCTION and not FRONTEND_URL:
    raise ImproperlyConfigured('FRONTEND_URL is required in production.')

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend'
    if IS_PRODUCTION
    else 'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Cabinet Aït El Hadj <no-reply@aitelhadj.local>')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = env_int('EMAIL_PORT', 587)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
