# Generated by Django 6.0.5 on 2026-05-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
