# Generated by Django 6.0.5 on 2026-05-17 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_case_number_case_case_type_case_court_and_more'),
        ('clients', '0001_initial'),
        ('finance', '0002_invoice_description_payment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('expense', 'Expense')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('paid', 'Paid')], max_length=20, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cases.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='clients.client')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
